package launch;

import org.openqa.selenium.By;
import org.openqa.selenium.WebElement;

public class LaunchBrowser extends BaseClass {

	public static void main(String[] args) throws Exception {
		launchrowser("https://www.toolsqa.com/automation-practice-form/");
		driver.manage().window().maximize();
		WebElement e = driver.findElement(By.xpath("//input[@name='firstname']"));
		type(e,"murali");
		WebElement q = driver.findElement(By.xpath("//input[@id='lastname']"));
		type(q,"krishna");
		WebElement w = driver.findElement(By.xpath("//button[text()='Simple Button']"));
		w.click();
		Thread.sleep(2000);
		WebElement t = driver.findElement(By.xpath("//input[@id=\"sex-1\"]"));
		click(t);
		WebElement y = driver.findElement(By.id("exp-2"));
		click(y);
		Thread.sleep(2000);
		WebElement d = driver.findElement(By.xpath("//input[@id=\"datepicker\"]"));
		type(d, "11 nov 2019");
		WebElement f = driver.findElement(By.xpath("//input[@id=\"profession-0\"]"));
		click(f);
		WebElement g = driver.findElement(By.xpath("//input[@id=\"profession-1\"]"));
		click(g);
		WebElement j = driver.findElement(By.xpath("//a[text()='Selenium Automation Hybrid Framework']"));
		click(j);
		WebElement k = driver.findElement(By.xpath("//a[text()='Test File to Download']"));
		click(k);
		WebElement l = driver.findElement(By.xpath("//input[@id=\"tool-0\"]"));
		click(l);
		WebElement x = driver.findElement(By.xpath("//input[@id=\"tool-1\"]"));
		click(x);
		WebElement z = driver.findElement(By.xpath("//input[@id=\"tool-2\"]"));
		click(z);
		WebElement c = driver.findElement(By.xpath("//select[@id='continents']"));
		WebElement v = driver.findElement(By.xpath("(//option[text()='Asia'])[1])"));
		click(v);
		WebElement b = driver.findElement(By.xpath("(//option[text()='Europe'])[1]"));
		click(b);
		WebElement n = driver.findElement(By.xpath("(//option[text()='Africa'])[1]"));
		click(n);
		WebElement m = driver.findElement(By.xpath("(//option[text()='Australia'])[1]"));
		click(m);
		WebElement qw = driver.findElement(By.xpath("(//option[text()='South America'])[1]"));
		click(qw);
		WebElement er = driver.findElement(By.xpath("(//option[text()='North America'])[1]"));
		click(er);
		WebElement ty = driver.findElement(By.xpath("(//option[text()='Antarctica'])[1]"));
		click(ty);
		WebElement yu = driver.findElement(By.xpath("(//option[text()='Asia'])[2])"));
		click(yu);
		WebElement io = driver.findElement(By.xpath("(//option[text()='Europe'])[2]"));
		click(io);
		WebElement op = driver.findElement(By.xpath("(//option[text()='Africa'])[2]"));
		click(op);
		WebElement pa = driver.findElement(By.xpath("(//option[text()='Australia'])[2]"));
		click(pa);
		WebElement as = driver.findElement(By.xpath("(//option[text()='South America'])[2]"));
		click(as);
		WebElement sd = driver.findElement(By.xpath("(//option[text()='North America'])[2]"));
		click(sd);
		WebElement df = driver.findElement(By.xpath("(//option[text()='Antarctica'])[2]"));
		click(df);
		WebElement fg = driver.findElement(By.xpath("//option[text()='Browser Commands']"));
		click(fg);
		WebElement gh = driver.findElement(By.xpath("//option[text()='Navigation Commands']"));
		click(gh);
		WebElement hj = driver.findElement(By.xpath("//option[text()='Navigation Commands']"));
		click(hj);
		WebElement jk = driver.findElement(By.xpath("//option[text()='Wait Commands']"));
		click(jk);
		WebElement kl = driver.findElement(By.xpath("//option[text()='WebElement Commands']"));
		click(kl);
		WebElement zx = driver.findElement(By.xpath("//button[text()='Button']"));
		click(zx);
		WebElement xc = driver.findElement(By.xpath("//button[text()='Button 2']"));
		click(xc);
		WebElement cv = driver.findElement(By.xpath("//button[text()='Button 3']"));
		click(cv);
		WebElement vb = driver.findElement(By.xpath("//button[text()='Button 4']"));
		click(vb);
		WebElement bn = driver.findElement(By.xpath("//span[text()='Text1']"));
		String qwe = bn.getText();
		System.out.println(qwe);
		WebElement wer = driver.findElement(By.xpath("//span[text()='Text2']"));
		String ert = wer.getText();
		System.out.println(ert);
		WebElement rty = driver.findElement(By.xpath("//li[text()='Coffee']"));
		String tyu = rty.getText();
		System.out.println(tyu);
		WebElement yui = driver.findElement(By.xpath("//li[text()='Tea'])"));
		String uio = yui.getText();
		System.out.println(uio);
		WebElement iop = driver.findElement(By.xpath("//li[text()='Milk']"));
		String opa = iop.getText();
		System.out.println(opa);
		WebElement pas = driver.findElement(By.xpath("//li[text()='skimmed Milk']"));
		String asd = pas.getText();
		System.out.println(asd);
		driver.quit();		
		}

}
